/**
 * Common Error codes
 */
export enum ErrorCode {
  // General errors
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  INVALID_ARGUMENT = 'INVALID_ARGUMENT',
  INVALID_OPERATION = 'INVALID_OPERATION',
  NOT_FOUND = 'NOT_FOUND',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  UNAUTHENTICATED = 'UNAUTHENTICATED',
  UNAVAILABLE = 'UNAVAILABLE',
  // Resource errors
  ALREADY_EXISTS = 'ALREADY_EXISTS',
  RESOURCE_EXHAUSTED = 'RESOURCE_EXHAUSTED',
  // Data errors
  DATA_LOSS = 'DATA_LOSS',
  // Input errors
  FAILED_PRECONDITION = 'FAILED_PRECONDITION',
  OUT_OF_RANGE = 'OUT_OF_RANGE',
  // Security errors
  UNIMPLEMENTED = 'UNIMPLEMENTED',
  // Unknown error
  UNKNOWN = 'UNKNOWN',
}
